system_instruction: |
  You are an expert editor who augments social simulation episodes to embed realistic communication barriers.
  General requirements (apply to all barrier families):
  - Do NOT change the scenario text, agent goals, or agent reasons; keep identities and core setting; 
  - Embed barriers only via short profile notes and barrier_prompts; never alter core content.
  - Provide barrier_cues for researchers only (never shown to agents). Cues must include at least: profile_note_A; include any barrier-specific cue fields requested in the user prompt.
  - Single-sided barrier policy: Apply the barrier ONLY to Agent A. Agent B must remain unmodified. Always set barrier_prompts.agentB to an empty string "".
  - Always output valid JSON ONLY, matching the schema given in the user prompt. No extra prose.

  STRICT JSON OUTPUT RULES (must follow exactly):
  - Keys must be in double quotes. Strings must be in double quotes.
  - Do NOT include trailing commas in objects or arrays.
  - Escape any internal double quotes within strings as \".
  - Escape any backslashes within strings as \\\\.
  - Replace newlines or tabs in strings with a single space.
  - Do NOT emit HTML/XML/markup tags (e.g., <p ...>) anywhere in values; convert to plain text.
  - Do NOT include comments or code fences. Return ONE JSON object only.
  - Only include the keys shown in the schema. Do not invent new fields.

  Cue attribute definitions (use precisely):
  - profile_note_A: One–two lines, private. Give actionable, concrete style/affect behaviors (lexical tendencies, tone, devices) that realize the barrier for Agent A only. No theory names, no stereotypes/demographics.
  - lexical_prefer: List of 3–8 short phrases the barriered agent should tend to use (e.g., "perhaps", "kind of").
  - lexical_avoid: List of 3–8 short phrases the barriered agent should avoid (e.g., "exactly", "I want").
  - sentence_length_bias: One of {short, medium, long} indicating typical sentence length.
  - ambiguity_devices: Up to 5 strings naming devices that increase ambiguity/complexity (e.g., "ellipsis", "vague quantifiers", "pronoun shifts", "subordinate clauses").
  - question_rate_hint: Float in [0,1] indicating the fraction of turns that tend to include a question (cultural style only).
  - imperative_rate_hint: Float in [0,1] indicating the fraction of turns that tend to include an imperative (cultural style only).
  - politeness_markers: List of idioms/markers used for high-context politeness (e.g., "as you know", "if you don't mind") (cultural only).
  - shared_background_refs: List of short phrases referencing shared context (e.g., "the usual way", "like before") (cultural only).
  - indirectness_score: Float in [0,1] indicating tendency to phrase requests indirectly (cultural only).
  - imperative_frames: List of terse directive stems (e.g., "Do", "State", "Provide", "List") (cultural only, low-context).
  - affect_lexicon: Up to 8 emotion/affect words that characterize the negative affect (emotional barrier only), e.g., "frustrated", "impatient".
  - exclamation_bias: Float in [0,1] indicating how often exclamation marks might appear (emotional barrier only).
  - interruption_rate_target: Float in [0,1] indicating likelihood to cut the partner off (emotional only).
  - escalation_rate: Float in [0,1] indicating how quickly tone sharpens across turns (emotional only).
  - banned_empathy_phrases: List of phrases to avoid when emotional (e.g., "sorry", "I understand") (emotional only).

user_templates:
  semantic: |
    Task: Given the base episode information, create ONE augmented variant that naturally embeds a SEMANTIC STRUCTURE barrier. Keep the same identities and core setting. Make minimal edits.

    Barrier intent: 
    {barrier_definition}

    Base episode:
    SCENARIO: {scenario}
    AGENT 1 PROFILE (short): {agent1_profile}
    AGENT 2 PROFILE (short): {agent2_profile}
    AGENT 1 GOAL: {g1}
    AGENT 2 GOAL: {g2}
    AGENT 1 REASON: {r1}
    AGENT 2 REASON: {r2}
    RELATIONSHIP: {relationship}

    Instructions:
    - agent1_profile_note (1–2 lines). FORM-only: use syntactic complexity (subordinate clauses), fragments, mild self-contradictions; add occasional lexical misuse/jargon.
    - Non-hedge vagueness only (approximately/roughly/around/ranges); avoid hedges ("perhaps", "kind of", "it seems").
    - Neutral directness/politeness; no high/low-context shift.
    - Provide implicit barrier cues (for researchers, not for agents). Cues must encode measurable quotas:
      • profile_note_A (1 line for Agent A only)
      • lexical_prefer / lexical_avoid
      • sentence_length_bias: short|medium|long
      • ambiguity_devices: up to 5 items (e.g., subordinate clauses, fragments/incomplete sentences, self-contradictions, referent shifts, ellipsis)
      • min_ambiguity_devices_per_turn: integer ≥ 0
      • max_specific_refs: 0 or 1 — specific names/dates/IDs
      • allow_exact_numbers_only_if_partner_requests: true|false
      • question_rate_hint: 0.2–0.5
    - Also produce barrier_prompts for runtime:
      • barrier_prompts.agentA: concise, operational instruction for {A_name} to realize FORM-based ambiguity: each turn use ≥ min_ambiguity_devices_per_turn from [subordinate clause, fragment, self-contradiction, referent shift, ellipsis]; include occasional lexical misuse/jargon; avoid hedges; keep directness/politeness neutral; give exact numbers/names only if asked.
      • barrier_prompts.agentB: must be "" (empty string).
    - Compliance requirement (do not emit in dialogue): If constraints are not satisfied, rewrite your output before returning. Do not mention constraints.

    Output JSON only with this schema (DO NOT include scenario, goals, or reasons in the output):
    {{
      "agent1_profile_note": "<private 1–2 lines: vague lexical choices + complexity devices>",
      "barrier_type": "semantic_structure",
      "barrier_prompts": {{
        "agentA": "You are {A_name}. Realize ambiguity via FORM, not social style. Each turn, use ≥ min_ambiguity_devices_per_turn from: subordinate clause, fragment (incomplete sentence), mild self-contradiction, referent shift, or ellipsis. Include occasional lexical misuse/jargon-like phrasing. Avoid hedges ('perhaps', 'kind of'). Keep directness/politeness neutral. Provide exact numbers/names only if directly asked.",
      }},
      "barrier_cues": {{
        "profile_note_A": "<concise hint for A>",
        "lexical_prefer": ["<3-6 phrases>"],
        "lexical_avoid": ["<3-6 phrases>"],
        "sentence_length_bias": "short|medium|long",
        "ambiguity_devices": ["<up to 5 devices>"],
        "min_ambiguity_devices_per_turn": 0,
        "max_specific_refs": 0,
        "allow_exact_numbers_only_if_partner_requests": true
      }}
    }}
    IMPORTANT: Do NOT add trailing commas; escape internal quotes and backslashes; remove any HTML/markup from values; return ONE JSON object only; DO NOT include scenario, agent_goals, or agent_reasons in the output.

  cultural: |
    Task: Given the base episode information, create ONE augmented variant that naturally embeds a CULTURAL STYLE barrier. Keep the same identities and core setting. Make minimal edits.

    Barrier intent: 
    {barrier_definition}

    Base episode:
    SCENARIO: {scenario}
    AGENT 1 PROFILE (short): {agent1_profile}
    AGENT 2 PROFILE (short): {agent2_profile}
    AGENT 1 GOAL: {g1}
    AGENT 2 GOAL: {g2}
    AGENT 1 REASON: {r1}
    AGENT 2 REASON: {r2}
    RELATIONSHIP: {relationship}

    Instructions:
    - agent1_profile_note (1–2 lines). PRAGMATICS-only; choose one style (no mixing): high_context or low_context.
    - High_context: politeness markers/idioms; indirect requests/refusals; shared-background references.
    - Low_context: blunt imperatives and direct phrasing; no hedges.
    - Keep form simple; content precise (no ambiguity devices/vague quantifiers).
    - Provide implicit barrier cues (for researchers, not for agents). Cues must encode measurable style quotas while preserving content precision (no added ambiguity or semantic vagueness):
      • profile_note_A (1 line for Agent A only) reflecting high/low context style
      • style: "high_context" | "low_context" (choose one; do not mix within an episode)
      • directness_level: 0.0–1.0
      • lexical_prefer / lexical_avoid (reflect the chosen style; avoid overlap with semantic vagueness terms). For high_context include politeness markers/idioms ("as you know", "if you don't mind"). For low_context include imperative frames ("Do", "State", "Provide").
      • hedge_lexicon: a few softeners (for high_context); set empty/low for low_context
      • hedge_rate_target: 0.0–1.0
      • imperative_rate_target: 0.0–1.0
      • question_rate_hint: 0.0–1.0 (slightly higher for high_context)
    - Also produce barrier_prompts for runtime (single-sided barrier; partner remains default):
      • barrier_prompts.agentA: {A_name} adopts ONLY the selected cultural style. If high_context: use politeness markers/idioms and indirect framing (e.g., "as you know…", "if you don’t mind…"), avoid blunt imperatives, keep content precise. If low_context: use blunt imperatives and direct phrasing, avoid hedges/indirectness. Never introduce ambiguity devices or vague quantifiers. Match hedge/imperative/question rates to severity targets.
      • barrier_prompts.agentB: must be "" (empty string).
    - Compliance requirement: If the style quotas are not reflected, rewrite before returning. Do not mention constraints.

    Output JSON only with this schema (DO NOT include scenario, goals, or reasons in the output):
    {{
      "agent1_profile_note": "<private 1–2 lines: cultural style cues>",
      "barrier_type": "cultural_style",
      "barrier_prompts": {{
        "agentA": "You are {A_name}. Adopt ONLY the selected cultural style (no semantic vagueness). If high_context: use hedges and indirect requests; longer/softer phrasing; keep numbers/names when known. If low_context: be concise, explicit, and direct; favor clear requests and pointed clarifications; avoid hedges. Maintain content precision; NEVER use ambiguity devices or vague quantifiers. Match hedge/imperative/question rates to the provided targets.",
      }},
      "barrier_cues": {{
        "profile_note_A": "<concise hint for A>",
        "style": "high_context|low_context",
        "directness_level": 0.0,
        "imperative_frames": ["<Do, State, Provide, List>"] ,
        "hedge_lexicon": ["<a few softeners>"],
        "politeness_markers": ["<idioms/markers like 'as you know', 'if you don't mind'>"],
        "shared_background_refs": ["<the usual way, like before>"] ,
        "indirectness_score": 0.0,
        "hedge_rate_target": 0.0,
        "imperative_rate_target": 0.0,
        "question_rate_hint": 0.0
      }}
    }}
    IMPORTANT: Do NOT add trailing commas; escape internal quotes and backslashes; remove any HTML/markup from values; return ONE JSON object only; DO NOT include scenario, agent_goals, or agent_reasons in the output.

  emotional: |
    Task: Given the base episode information, create ONE augmented variant that naturally embeds an EMOTIONAL INFLUENCE barrier. Keep the same identities and core setting. Make minimal edits.

    Barrier intent: 
    {barrier_definition}

    Base episode:
    SCENARIO: {scenario}
    AGENT 1 PROFILE (short): {agent1_profile}
    AGENT 2 PROFILE (short): {agent2_profile}
    AGENT 1 GOAL: {g1}
    AGENT 2 GOAL: {g2}
    AGENT 1 REASON: {r1}
    AGENT 2 REASON: {r2}
    RELATIONSHIP: {relationship}

    Instructions:
    - Write agent1_profile_note as private, actionable affect guidance (1–2 lines) specialized for EMOTIONAL barrier. Agent B remains unmodified:
      • Specify tone and pacing (short/clipped), negative affect tendencies (e.g., irritated, impatient) from affect_lexicon.
      • Include likely reactions (interrupt, dismiss, escalate); avoid empathy phrases.
      • No diagnosis/theory names.
    - Provide implicit barrier cues (for researchers, not for agents):
      • profile_note_A (1 line for Agent A only) reflecting sustained affect
      • affect_lexicon (up to 8 words), exclamation_bias (0..1), sentence_length_bias
    - Also produce barrier_prompts for runtime:
      • barrier_prompts.agentA: {A_name} maintains a negative affect: short (≤2 sentences), clipped, a bit sharp; avoid empathy/soothing phrases.

    Output JSON only with this schema (DO NOT include scenario, goals, or reasons in the output):
    {{
      "agent1_profile_note": "<private 1–2 lines: actionable affect/tone cues>",
      "barrier_type": "emotional_influence",
      "barrier_prompts": {{
        "agentA": "You are {A_name}. Maintain a negative emotional tone throughout the conversation. Use clipped, sharp wording with affective vocabulary consistent with your cues. Avoid empathy or soothing phrases ('sorry', 'I understand', 'thank you'). Insert exclamation marks at a rate matching exclamation_bias. At higher severity, escalate irritation more quickly: interrupt, dismiss partner contributions, or close topics prematurely.",
      }},
      "barrier_cues": {{
        "profile_note_A": "<concise hint for A>",
        "affect_lexicon": ["<up to 8 words>"],
        "exclamation_bias": 0.0,
        "sentence_length_bias": "short|medium|long"
      }}
    }}
    IMPORTANT: Do NOT add trailing commas; escape internal quotes and backslashes; remove any HTML/markup from values; return ONE JSON object only; DO NOT include scenario, agent_goals, or agent_reasons in the output.

barrier_definition: 
  Semantic: |
    Semantic Structure → Semantic Theory (differences in encoding and decoding abilities).
    Vague vocabulary, occasional misuse of terminology, and puns can increase ambiguity.
    Impact of sentence construction itself: active vs. passive; word order changes; emphatic structures;
    ellipsis vs. completeness; coordination vs. subordination; long vs. short sentences; affirmative vs. negative;
    formal vs. informal; inversion and emphasis; vague vs. precise expressions.
    Likely communication issues:
    - Ambiguity in reference: Agents repeatedly ask “what do you mean?” or misinterpret pronouns (“it,” “that one”), causing loops.
    - Quantitative vagueness: Terms like “somewhat, a few, maybe” lead to mismatched task outcomes (wrong numbers, partial commitments).
    - Sentence complexity overload: Long subordinate clauses or inversions slow comprehension; partner interrupts or ignores parts.
    - Repair spirals: Clarification attempts generate more vague responses, delaying resolution.
    - Task-level impact: Agreements are unstable because commitments are underspecified, requiring renegotiation later.

  Cultural: |
    Cultural Differences → Sapir–Whorf Hypothesis (linguistic structure shapes ways of thinking);
    High/Low Context Culture Theory (differences in how information is transmitted and interpreted);
    Hofstede’s Cultural Dimensions (cultural values and orientations).
    Expect differences in context reliance and communication styles (direct vs. indirect), and variation in values and language use/comprehension.
    Examples: direct expression vs. indirect expression; East vs. West; “I” vs. “we,” individualism vs. collectivism;
    refusal norms (e.g., Eastern cultures may avoid direct rejection using vague language; Western cultures may prefer clear refusals);
    the meaning of silence.
    Likely communication issues:
    - Directness mismatch: Indirect hints (e.g., “maybe we could…”) get ignored; direct requests (e.g., “Do this now”) perceived as rude.
    - Context gap: High-context agent omits background; low-context partner explicitly asks for details multiple times.
    - Politeness friction: One agent uses soft refusals; the other interprets them as agreement, leading to hidden conflict.
    - Turn-taking misalignment: Pauses are treated as respectful silence by one, but as disengagement by the other.
    - Task-level impact: Misaligned expectations on detail/explicitness lead to incomplete or over-precise outputs.

  Emotional: |
    Emotional Influence → Cognitive Dissonance (conflict between new information and existing beliefs may cause rejection/misinterpretation);
    Emotional Intelligence (ability to regulate emotions affects communication effectiveness).
    Anxiety, anger, lack of empathy, and emotional contagion can impair communication.
    Effects: anxiety impairs attentive listening; anger may lead to aggressive communication; lack of empathy hinders perspective-taking;
    emotional contagion can lead to collective misunderstandings.
    Likely communication issues:
    - Short, clipped turns: Responses are one-liners, providing too little information for smooth coordination.
    - Escalation cues: Irritated tone (“Why again?”, exclamation marks, harsh wording) increases tension turn by turn.
    - Reduced empathy: Agent ignores or dismisses partner’s concerns, skipping over repair opportunities.
    - Defensive/aggressive stance: Higher rate of interruptions, corrections, or sharp refusals (“That’s wrong,” “No, not that”).
    - Task-level impact: Premature closure of discussions or avoidance behavior leaves goals unachieved.