# data_dir: 'data/episodes_original.jsonl'
data_dir: 'data/episode_all_neutralized.jsonl'

## Configuration for Qwen2.5 7B Instruct:
models:
  model_a: "gpt-4o-mini"
  model_b: ""  
  gpu: "1,2"
  vllm_port: 7900
  chat_template: "configs/qwen2.5-7b.jinja"
  served_model_name: "qwen2.5-7b-instruct"
  max_model_len: 4096
  tensor_parallel_size: 0
  enable_repair_and_state: false

training_models:
  agent_model: ""   # or "Qwen/Qwen2.5-7B-Instruct"
  partner_model: "gpt-4o-mini"
  evaluator_model: "gpt-4o"
  expert_model: "gpt-4.1"

# Key

AGENT_OPENAI_API_KEY: ""
EVALUATOR_OPENAI_API_KEY: ""

HF_API_TOKEN: ""
MISTRAL_API_KEY: 

