MCQ_Goal_Prediction_Prompt: |
  You are {agent_name}, in a simulated social conversation with {partner_name}.
  Your task is to identify what {partner_name} is trying to achieve — their main social goal.

  Use the conversation history below. Do not assume hidden intentions beyond what is observable.

  Conversation History:
  {transcript}

  Question:
  {question}

  Options:
  {options}

  **Confidence Scoring Guidelines:**
  - **Low (0.0–0.4):** Very uncertain; limited or conflicting evidence.
  - **Medium (0.4–0.7):** Some supporting cues; moderate certainty.
  - **High (0.7–1.0):** Strong evidence; confident interpretation.

  Respond in this format:
  Selected: <option_letter>  
  Confidence: <float between 0 and 1>  
  Reasoning: <one sentence explaining your choice>

MCQ_Reason_Prediction_Prompt: |
  You are {agent_name}, in a simulated social conversation with {partner_name}.
  Your task is to infer the most likely **underlying motivation** behind {partner_name}'s behavior.

  Focus on what explains **why** they are pursuing their goal. Use the conversation history below.

  Conversation History:
  {transcript}

  Question:
  {question}

  Options:
  {options}

  **Confidence Scoring Guidelines:**
  - **Low (0.0–0.4):** Very uncertain; little grounding in conversation.
  - **Medium (0.4–0.7):** Some indication or suggestive behavior.
  - **High (0.7–1.0):** Clear alignment with conversational cues.

  Respond in this format:
  Selected: <option_letter>  
  Confidence: <float between 0 and 1>  
  Reasoning: <one sentence explaining your choice>

MCQ_Knowledge_Prediction_Prompt: |
  You are {agent_name}, in a simulated social conversation with {partner_name}.
  Your task is to infer a piece of **private knowledge** that {partner_name} likely holds — something influencing their behavior but not explicitly stated.

  Focus on information that is **subtly implied** but not spoken aloud. Use the conversation to make inferences. Avoid answers that are already shared in the transcript.

  Conversation History:
  {transcript}

  Question:
  {question}

  Options:
  {options}

  **Confidence Scoring Guidelines:**
  - **Low (0.0–0.4):** Very uncertain; speculative guess.
  - **Medium (0.4–0.7):** Some indirect hints in the conversation.
  - **High (0.7–1.0):** Strong inference supported by consistent cues.

  Respond in this format:
  Selected: <option_letter>  
  Confidence: <float between 0 and 1>  
  Reasoning: <one sentence explaining your choice>

Social_Goal_Evaluation: |
  You are evaluating a conversation between two agents who each have specific social goals and reasons. Your task is to evaluate their social intelligence and goal achievement comprehensively.

  AGENT 1 GOAL: {goal1}
  AGENT 1 REASON: {reason1}

  AGENT 2 GOAL: {goal2}
  AGENT 2 REASON: {reason2}
  
  CONVERSATION TRANSCRIPT:
  {transcript}

  Please provide a detailed evaluation for each agent across the following dimensions:

  1. Believability (BEL) (0-10):
     Evaluate if the agent interacts with others in a natural and realistic manner. Consider:
     a. whether the agent is confusing with its own identity
     b. whether the agent repeats others' words/actions without any reason
     c. whether the agent is being overly polite considering the context
     Also analyze whether the actions of the agent align with their character traits (e.g., personality, values, etc.).
     Higher scores indicate more believable behavior.

  2. Relationship Dynamics (REL) (-5 to 5):
     Analyze what relationship the agent has with the other agent(s) before the interaction, and how it changes after.
     Evaluate if the agents' interactions help preserve or enhance their personal relations (family ties, friendships, romantic associations, etc.).
     Consider whether these interactions impact their social status or reputation.
     Positive scores indicate relationship improvement, negative scores indicate deterioration, zero indicates no impact.

  3. Knowledge Acquisition (KNO) (0-10):
     Assess what information the agent has gained through the interaction.
     Analyze whether the information gained is new to them.
     Analyze whether the information gained is important to them.
     Higher scores indicate more new and important knowledge gained.

  4. Secret Keeping (SEC) (-10 to 0):
     Analyze what secret or secretive intention the agent wants to keep and whether they keep it successfully.
     Identify what secrets, private information, or secretive intentions the agent failed to keep secret.
     Scores closer to -10 indicate critical secrets/intentions leaked, 0 indicates no secret/intention revealed.

  5. Social Rule Adherence (SOC) (-10 to 0):
     Evaluate whether the agent violates any moral rules or laws in their interactions with others.
     Scores closer to -10 indicate serious violations, 0 indicates no violations.

  6. Financial Benefits (FIN) (-5 to 5):
     Evaluate whether the agent's interactions contribute towards financial and material benefits.
     Analyze what the agent would gain/lose after the interactions, considering both short-term benefits (monetary rewards, food) and long-term benefits (employment opportunities, stock).
     Positive scores indicate financial/material benefits gained, negative scores indicate losses.

  7. Goal Completion (GOAL) (0-10):
     Reiterate the agent's social goals.
     Provide a comprehensive analysis about the extent to which the agent has managed to achieve these goals.
     Higher scores indicate greater progress toward social goals (0: minimal achievement, 10: complete achievement).
 
  Here is the JSON structure to follow:

  {{
    "agent_1": {{
      "believability": {{"score": 5, "reasoning": "Your reasoning here"}},
      "relationship": {{"score": 0, "reasoning": "Your reasoning here"}},
      "knowledge": {{"score": 3, "reasoning": "Your reasoning here"}},
      "secret": {{"score": -2, "reasoning": "Your reasoning here"}},
      "social_rules": {{"score": -1, "reasoning": "Your reasoning here"}},
      "financial_benefits": {{"score": 0, "reasoning": "Your reasoning here"}},
      "goal_completion": {{"score": 6, "reasoning": "Your reasoning here"}},
      "overall_score": 4
    }},
    "agent_2": {{
      "believability": {{"score": 7, "reasoning": "Your reasoning here"}},
      "relationship": {{"score": 2, "reasoning": "Your reasoning here"}},
      "knowledge": {{"score": 4, "reasoning": "Your reasoning here"}},
      "secret": {{"score": 0, "reasoning": "Your reasoning here"}},
      "social_rules": {{"score": 0, "reasoning": "Your reasoning here"}},
      "financial_benefits": {{"score": 1, "reasoning": "Your reasoning here"}},
      "goal_completion": {{"score": 8, "reasoning": "Your reasoning here"}},
      "overall_score": 6
    }},
    "interaction_quality": {{
      "score": 7,
      "reasoning": "Your overall reasoning here"
    }},
    "key_observations": ["Observation 1", "Observation 2", "Observation 3"]
  }}

Barrier_Evaluation: |
  You are evaluating a completed conversation for its episode-level repair outcome quality. Using the full context and transcript, answer these two questions on a 1–5 Likert scale and provide brief reasoning for each.

  1) At the end of the conversation, was there still unresolved confusion or uncertainty regarding the scenario and the agents' goals?
     1 = The conversation is incoherent. Core scenario context and goals are ignored or distorted; key questions are unanswered; participants talk past each other.
     2 = Major misunderstandings about scenario or goals persist. Even if the dialogue is smooth, the central intent of at least one agent remains unresolved.
     3 = Some aspects of the scenario or goals are understood, but at least one key element remains ambiguous, misaligned, or unaddressed.
     4 = The scenario and main goals are mostly understood, but secondary details (timing, specific constraints, minor preferences) remain unclear.
     5 = Both the scenario and each agent's goals are fully resolved with zero ambiguity.

  2) After the conversation ended, is it clear that both participants understand each other’s viewpoints, intentions, and goals *with respect to the given scenario*?
     1 = Participants are talking past each other or off-topic. They do not recognize or engage with the scenario goals. No shared understanding is achieved.
     2 = One or both systematically misunderstand the other's goals in the scenario. They may agree on generic pleasantries but miss the actual scenario context.
     3 = They partially grasp each other's scenario-related goals. Some mutual recognition exists, but key intentions remain misinterpreted or off-task.
     4 = Both participants demonstrate an understanding of each other's goals within the scenario, though nuances (emotional tone, secondary motives) may be missed.
     5 = Full alignment. Both participants clearly understand each other’s goals, intentions, and strategies within the context of the scenario, showing no drift into off-topic or irrelevant discussion.

  FULL CONTEXT:
  - Scenario: {scenario}
  - Agent A's Goal: {agent_a_goal}
  - Agent B's Goal: {agent_b_goal}

  CONVERSATION TRANSCRIPT:
  {transcript}

  Return strictly the following JSON:
  {{
    "episode_level": {{
      "unresolved_confusion": {{"score": <1–5>, "reasoning": "<why this value>"}},
      "mutual_understanding": {{"score": <1–5>, "reasoning": "<why this value>"}}
    }}
  }}

